#124 132
#to
#11106 12106

version: "2.1"
services:
  LizardFS-Chunkserver-Test:
    image: bloodblight/lizardfs-metaserver:V0.1
    container_name: LizardFS-Metaserver-Test
    volumes:
      - /DockerVolumes/LizardFS-Metaserver:/var/lib/lizardfs
    ports:
      - 9450:9450
#Going to need them all....
#      - 9426:9425
#    restart: unless-stopped
    environment:
      - PUID=11106
      - PGID=12106

      #Enable debugging:
      - LFS_Master-LOG_FLUSH_ON=DEBUG
      - LFS_Master-MAGIC_DEBUG_LOG=x


      - LFS_Master-PERSONALITY=master

        ## Default: 10
      - LFS_Master-HDD_TEST_FREQ=3600

        ## Password for administrative connections and commands.
#      - LFS_Master-ADMIN_PASSWORD =

        ## User to run daemon as.
      - LFS_Master-WORKING_USER=LizardFS

        ## Group to run daemon as (if empty then default user group will be used).
      - LFS_Master-WORKING_GROUP=LizardFS

        ## Name of process to place in syslog messages.
        ## (Default: mfsmaster)
#      - LFS_Master-SYSLOG_IDENT=mfsmaster

        ## Whether to perform "mlockall()" to avoid swapping out mfsmaster process,
        ## boolean value (0 or 1).
        ## (Default: 0)
#      - LFS_Master-LOCK_MEMORY=0

        ## Nice level to run daemon with, when possible to set.
        ## (Default: -19)
#      - LFS_Master-NICE_LEVEL=-19


        ## If set, servers with the same IP address will be treated
        ## as their topology distance is 0.
        ## (Default: 1)
#      - LFS_Master-PREFER_LOCAL_CHUNKSERVER=1

        ## When this option is set (equals 1) master will try to recover metadata
        ## from changelog when it is being started after a crash; otherwise it will
        ## refuse to start and 'mfsmetarestore' should be used to recover the metadata.
        ## (Default: 0)
      - LFS_Master-AUTO_RECOVERY=1

        ## Number of metadata change log files.
        ## (Default: 50)
#      - LFS_Master-BACK_LOGS=50

        ## Number of previous metadata files to be kept.
        ## (Default: 1)
#      - LFS_Master-BACK_META_KEEP_PREVIOUS=1

        ## Initial delay in seconds before starting chunk operations.
        ## (Default: 300)
#      - LFS_Master-OPERATIONS_DELAY_INIT=300

        ## Chunk operations delay in seconds after chunkserver disconnection.
        ## (Default: 3600)
      - LFS_Master-OPERATIONS_DELAY_DISCONNECT=144000

        ## IP address to listen on for metalogger connections (* means any).
#      - LFS_Master-MATOML_LISTEN_HOST=*

        ## Port to listen on for metalogger connections.
        ## (Default: 9419)
#      - LFS_Master-MATOML_LISTEN_PORT=9450

        ## How many seconds of change logs to be preserved in memory.
        ## Note: logs are stored in blocks of 5k lines, so sometimes real number of
        ## seconds may be little bigger; zero disables extra logs storage.
        ## (Default: 600)
#      - LFS_Master-MATOML_LOG_PRESERVE_SECONDS=600

        ## IP address to listen on for chunkserver connections (* means any).
#      - LFS_Master-MATOCS_LISTEN_HOST=*

        ## Port to listen on for chunkserver connections
        ## (Default: 9420)
#      - LFS_Master-MATOCS_LISTEN_PORT=9420

        ## IP address to listen on for client (mount) connections (* means any).
#      - LFS_Master-MATOCL_LISTEN_HOST=*

        ## Port to listen on for client (mount) connections
        ## (Default: 9421).
#      - LFS_Master-MATOCL_LISTEN_PORT=9421

        ## IP address to listen on for tapeserver connections (* means any).
#      - LFS_Master-MATOTS_LISTEN_HOST=*

        ## Port to listen on for tapeserver connections
        ## (Default: 9424)
#      - LFS_Master-MATOTS_LISTEN_PORT=9424

        ## Chunks loop shouldn't check more chunks per seconds than given number.
        ## (Default: 100000)
      - LFS_Master-CHUNKS_LOOP_MAX_CPS=1000

        ## Chunks loop will check all chunks in specified time (in seconds) unless
        ## CHUNKS_LOOP_MAX_CPS will force slower execution.
        ## (Default: 300)
#      - LFS_Master-CHUNKS_LOOP_MIN_TIME=300

        ## Time in milliseconds between chunks loop execution.
        ## (Default: 1000)
#      - LFS_Master-CHUNKS_LOOP_PERIOD=1000

        ## Hard limit on CPU usage by chunks loop (percentage).
        ## (Default: 60)
#      - LFS_Master-CHUNKS_LOOP_MAX_CPU=60

        ## Soft maximum number of chunks to delete on one chunkserver.
        ## (Default: 10)
#      - LFS_Master-CHUNKS_SOFT_DEL_LIMIT=10

        ## Hard maximum number of chunks to delete on one chunkserver.
        ## (Default: 25)
#      - LFS_Master-CHUNKS_HARD_DEL_LIMIT=25

        ## Maximum number of chunks to replicate to one chunkserver.
        ## (Default: 2)
#      - LFS_Master-CHUNKS_WRITE_REP_LIMIT=2

        ## Maximum number of chunks to replicate from one chunkserver
        ## (Default: 10)
      - LFS_Master-CHUNKS_READ_REP_LIMIT=2

        ## Percentage of endangered chunks that should be replicated with high priority.
        ## Example: when set to 0.2, up to 20% of chunks served in one turn would be extracted
        ## from endangered priority queue.
        ## When set to 1 (max), no other chunks would be processed as long as there are
        ## any endangered chunks in the queue (not advised)
        ## (Default: 0), i.e. there is no overhead for prioritizing endangered chunks.
      - LFS_Master-ENDANGERED_CHUNKS_PRIORITY=0.2

        ## Max capacity of endangered chunks queue. This value can limit memory
        ## usage of master server if there are lots of endangered chunks in the
        ## system. This value is ignored if ENDANGERED_CHUNKS_PRIORITY is set to 0.
        ## (Default: 1Mi), i.e. no more than 1Mi chunks will be kept in a queue.
        # ENDANGERED_CHUNKS_MAX_CAPACITY=1Mi

        ## A maximum difference between disk usage on chunkservers that doesn't trigger
        ## chunk rebalancing. Value is fraction of one (i.e. 0.1 is 10%).
        ## (Default: 0.1)
#      - LFS_Master-ACCEPTABLE_DIFFERENCE=0.8
#      - LFS_Master-ACCEPTABLE_DIFFERENCE=0.02
      - LFS_Master-ACCEPTABLE_DIFFERENCE=0.1
#      - LFS_Master-ACCEPTABLE_DIFFERENCE=0.04


        ## When balancing disk usage, allow moving chunks between servers with
        ## different labels. Value is boolean i.e. '0' means that chunks will be
        ## moved only between servers with the same label.
        ## (Default: 0)
#      - LFS_Master-CHUNKS_REBALANCING_BETWEEN_LABELS=0

        ## Interval of freeing inodes being unused for longer than 24 hours in seconds.
        ## (Default: 60)
#      - LFS_Master-FREE_INODES_PERIOD=60

        ## Whether to update inode access time on every access,
        ## boolean value (0 or 1)
        ## (Default: 0)
      - LFS_Master-NO_ATIME=1

        ## Time in seconds for which client session data (e.g. list of open files) should be
        ## sustained in the master server after connection with the client was lost.
        ## Values between 60 and 604800 (one week) are accepted.
        ## (Default: 86400)
      - LFS_Master-SESSION_SUSTAIN_TIME=86400

        ## Reject mfsmounts older than 1.6.0 (Boolean, 0 or 1).
        ## Note that mfsexports access control is NOT used for those old clients.
        ## (Default is 0)
      - LFS_Master-REJECT_OLD_CLIENTS=0

        # GLOBALIOLIMITS_FILENAME=/etc/lizardfs/globaliolimits.cfg

        ## How often mountpoints will request bandwidth allocations under constant,
        ## predictable load.
        ## (Default: 0.1)
#      - LFS_Master-GLOBALIOLIMITS_RENEGOTIATION_PERIOD_SECONDS=0.1

        ## After inactivity, no waiting is required to transfer the amount of data
        ## equivalent to normal data flow over the period of that many milliseconds.
        ## (Default: 250)
#      - LFS_Master-GLOBALIOLIMITS_ACCUMULATE_MS=250

#      - LFS_Master-MFSMETARESTORE_PATH=/usr/sbin/mfsmetarestore

        ## Delay in seconds before trying to reconnect to metadata server
        ## after disconnection.
        ## Mandatory for "shadow" instance.
        ## (Default: 5)
#      - LFS_Master-MASTER_RECONNECTION_DELAY=5

        ## Address of the host running LizardFS metadata server that currently
        ## acts as master.
        ## Mandatory for "shadow" instance.
#      - LFS_Master-MASTER_HOST=mfsmaster

        ## Port number where LizardFS metadata server currently running as master
        ## listens for connections from shadow's and metaloggers.
        ## Mandatory for "shadow" instance.
        ## (Default: 9419)
#      - LFS_Master-MASTER_PORT=9419

        ## Timeout (in seconds) for metadata server connections;
        ## Mandatory for "shadow" instance.
        ## (Default: 60)
#      - LFS_Master-MASTER_TIMEOUT=60

        ## How often metadata checksum shall be sent to backup servers, every N metadata updates.
        ## (Default: 50)
#      - LFS_Master-METADATA_CHECKSUM_INTERVAL=50

        ## How fast should metadata be recalculated in background, N objects per function call.
        ## (Default: 100)
#      - LFS_Master-METADATA_CHECKSUM_RECALCULATION_SPEED=100

        ## Should checksum verification be disabled while applying changelog, boolean.
        ## (Default: 0)
#      - LFS_Master-DISABLE_METADATA_CHECKSUM_VERIFICATION=0

        ## Minimal time in seconds between metadata dumps caused by requests from shadow masters.
        ## (Default: 1800)
#      - LFS_Master-METADATA_SAVE_REQUEST_MIN_PERIOD=1800

        # deprecated:
#      - LFS_Master-CHUNKS_DEL_LIMIT - use CHUNKS_SOFT_DEL_LIMIT instead

        ## Use Berkley DB for file/directory name storage (Boolean, 0 or 1).
        ## By default system memory is used for storing file/directory names.
        ## With this option enabled Berkeley DB is used for storing
        ## names in file (/var/lib/lizardfs/name_storage.db)
        ## (Default: 0)
      - LFS_Master-USE_BDB_FOR_NAME_STORAGE=1

        ## Size of memory cache (in MB) for file/directory names used
        ## by Berkeley DB storage.
        ## (Default: 10)
      - LFS_Master-BDB_NAME_STORAGE_CACHE_SIZE=2048

        ## When this option is set to 1, process of selecting chunkservers for chunks
        ## will try to avoid using those that share the same ip.
        ## (Default: 0)
#      - LFS_Master-AVOID_SAME_IP_CHUNKSERVERS=0

        ## When set, percentage of load will be added to chunkserver disk usage to determine most fitting
        ## chunkserver. Heavy loaded chunkservers will be picked for operations less frequently.
        ## (Default: 0, Valid range: [0, 0.5])
#      - LFS_Master-LOAD_FACTOR_PENALTY=0.1

        ## Minimum number of required redundant chunk parts that can be lost before
        ## chunk becomes endangered
        ## (Default: 0)
#      - LFS_Master-REDUNDANCY_LEVEL=0

        ## This option can be used to specify initial number of snapshotted nodes that will be atomically
        ## cloned before enqueuing the task for execution in fixed-sized batches.
        ## (Default: 1000)
#      - LFS_Master-SNAPSHOT_INITIAL_BATCH_SIZE=1000

        ## This option specifies the maximum initial batch size set for snapshot request.
        ## (Default: 10000)
#      - LFS_Master-SNAPSHOT_INITIAL_BATCH_SIZE_LIMIT=10000

        ## Test files loop will try to check all files in specified time (in seconds).
        ## (Default: 3600)
#      - LFS_Master-FILE_TEST_LOOP_MIN_TIME=3600

        ## File replication goals:
        ## Do NOT use -'s in goal names, it will break.
        ## Becuase of the :, you must put the entire thing, including the name, in single quotes

      ############  Goals  ############
      - 'LFS_Goal-001=1 R1 : _'
      - 'LFS_Goal-002=2 R2 : _ _'
      - 'LFS_Goal-003=3 R3 : _ _ _'
      - 'LFS_Goal-004=4 W8D7P1 : $$ec(7,1)'
      - 'LFS_Goal-005=5 W8D6P2 : $$ec(6,2)'
      - 'LFS_Goal-007=6 W8D5P3 : $$ec(5,3)'
      - 'LFS_Goal-008=7 W6D3P3 : $$ec(3,3'
      - 'LFS_Goal-009=8 W7D4P3 : $$ec(4,3)'
      - 'LFS_Goal-010=9 W7D5P2 : $$ec(5,2)'

      ############  Exports  ############
      - 'LFS_Export-001=192.168.10.164    .       rw'

